= Deathworld, by Harri Harrison

sprawled:: <<pagina, p.>> 2. s-a tolănit.
sprawl::: [sprɔ:l] https://en.wiktionary.org/wiki/sprawl[through a Proto-Germanic form cognate with *spreutaną (“to sprout”)].
sproute:::: [spraut] <<intranz, _vi_.>> a țâșni.

stein:: [staɪn] p. 2. pahar special de bere. https://en.wiktionary.org/wiki/stein[A beer mug, usually made of ceramic or glass].

limply:: p. 2. alene, domol, fără vlagă.
limp::: [lɪmp] _adj._ neputincios; țeapăn; amorțit. _vi._ a șchiopăta.
lump::: [lʌmp] _s._ bucată; bulgăr; umflătură. _vt._ a pune laolaltă; a înghiți.

casually:: 2 accidental, nelglijent, neoficial, provizoriu

blunt:: 2 tocit, necioplit, (d. persoane) sincer, greu de cap, prost

door slid:: 2 https://en.wiktionary.org/wiki/slid[simple past tense and past participle of slide]

slide:: a aluneca

chiseled:: 2 dăltuit, sculptat

slabs:: 2 plăci, dale, lespezi

strapped:: 2 prins

to strap:: a prinde

scowled:: 3 încruntat

swung:: 3 leganat, pendulat

holster:: 3 toc de pistol

aimed:: 3 țintit

aim:: țintă, ochire, direcție, sens, scop

to aim:: a ținti, a ochi; (to aim at) a îndrepta spre, a năzuit  

pitted:: 3 găurit, fără sămburi

flipped:: 3 plesnit

downed:: 3 coborât, doborât

mouthful:: 3 îmbucătura, remarcă corectă

mug:: 3 cană, oală

bridled:: 3 strunit

outdrawn:: 3 depășit 

offhand:: 3 improvizat, repezit

creaked:: 4 a scârțâit

ominously:: 4 amenințător

ominous:: ameminățor, prevestitor de rele; https://en.wiktionary.org/wiki/ominous#English[From Latin ominosus (“full of foreboding”), from omen (“forbidden fruit, omen”), from os (“the mouth”) + -men.]

dug:: 4 săpat

gleaming:: 4 

gleam:: a pâlpâui, a licări

glance:: 4 licărire, privire

forgeries:: 4 falsificări

bankroll:: 4 bani în cont

thoughtfully:: 4 cu grijă, cu considerație

lined:: 4 căptușit, înșiruit, liniat

though:: 4 cu toate că, deși

stamping:: 4 ștampilare, timbrare

paced back and forth:: 4

pace:: https://en.wiktionary.org/wiki/pace#Verb[To walk back and forth in a small distance]

jabbed:: 4 împins, înghiontit, vârât

ore:: [ɔ:] p. 5. minereu.

worn:: [wɔ:n] <<pagina, p.>> 5. _adj._ obosit; uzat. _vt._, _vi._ _part._ _trec._ _de la_ wear.
wear::: [wɛə] https://en.wiktionary.org/wiki/wear[Cognate to  Latin vestis (“garment”)]

== Lista de abrevieri

[[pagina]]p.:: pagina
[[intranz]]vi.:: verb intranzitiv
[[tranz]]vt.:: verb tranzitiv
[[part]]part. trec.:: participiu trecut

https://www.ling.upenn.edu/courses/Fall_2014/ling115/phonetics.html
