= Deathworld, by Harri Harrison


sprawled:: 2 se întinsese, se tolănise 

sprawl:: a se întinde, a sta tolănit, a se lafăi

stein:: 2 pahar special de bere; https://en.wiktionary.org/wiki/stein[A beer mug, usually made of ceramic or glass.]

limply:: 2 alene, domol, fără vlagă

limp:: adj. moale, flexibil, mlădios, lipsit de energie; verb. a șciopăta 

casually:: 2 accidental, nelglijent, neoficial, provizoriu

blunt:: 2 tocit, necioplit, (d. persoane) sincer, greu de cap, prost

door slid:: 2 https://en.wiktionary.org/wiki/slid[simple past tense and past participle of slide]

slide:: a aluneca

chiseled:: 2 dăltuit, sculptat

slabs:: 2 plăci, dale, lespezi

strapped:: 2 prins

to strap:: a prinde

scowled:: 3 încruntat

swung:: 3 leganat, pendulat

holster:: 3 toc de pistol

aimed:: 3 țintit

aim:: țintă, ochire, direcție, sens, scop

to aim:: a ținti, a ochi; (to aim at) a îndrepta spre, a năzuit  

pitted:: 3 găurit, fără sămburi

flipped:: 3 plesnit

downed:: 3 coborât, doborât

mouthful:: 3 îmbucătura, remarcă corectă

mug:: 3 cană, oală

bridled:: 3 strunit

outdrawn:: 3 depășit 

offhand:: 3 improvizat, repezit

creaked:: 4 a scârțâit

ominously:: 4 amenințător

ominous:: ameminățor, prevestitor de rele; https://en.wiktionary.org/wiki/ominous#English[From Latin ominosus (“full of foreboding”), from omen (“forbidden fruit, omen”), from os (“the mouth”) + -men.]

dug:: 4 săpat

gleaming:: 4 

gleam:: a pâlpâui, a licări

glance:: 4 licărire, privire

forgeries:: 4 falsificări

bankroll:: 4 bani în cont

thoughtfully:: 4 cu grijă, cu considerație

lined:: 4 căptușit, înșiruit, liniat

though:: 4 cu toate că, deși

stamping:: 4 ștampilare, timbrare

paced back and forth:: 4

pace:: https://en.wiktionary.org/wiki/pace#Verb[To walk back and forth in a small distance]

jabbed:: 4 împins, înghiontit, vârât

ore:: 5 minereu

worn:: 5 purtat, uzat
