= The Silmarillion, by J.R.R. Tolkine

hearkened:: 3 https://en.wiktionary.org/wiki/hearkened 

dwelling:: 3 https://en.wiktionary.org/wiki/dwelling locuință

brethren:: 3 https://en.wiktionary.org/wiki/brethren

mighty:: 3 https://en.wiktionary.org/wiki/mighty

bowed:: 3 https://en.wiktionary.org/wiki/bowed

ye:: 3 https://en.wiktionary.org/wiki/ye

kindled:: 3 https://en.wiktionary.org/wiki/kindled

forth:: 3 https://en.wiktionary.org/wiki/forth

woven:: 3 https://en.wiktionary.org/wiki/woven țesut

utterance:: 4 https://en.wiktionary.org/wiki/utterance rostire uuter - ro say

despondent:: 4 https://en.wiktionary.org/wiki/despondent descurajat From Latin despondere (“to give up, to abandon”).

faltered:: 4 https://en.wiktionary.org/wiki/faltered se clătina

attune:: 4 https://en.wiktionary.org/wiki/attune acorda

foundered:: 4 https://en.wiktionary.org/wiki/foundered scufundat From Middle French fondrer (“send to the bottom”), from Latin fundus (“bottom”)

raging:: 4 https://en.wiktionary.org/wiki/raging  in a state of rage

wrath:: 4 https://en.wiktionary.org/wiki/wrath mînie great anger (formal or old-fashioned)

assuaged::
4
https://en.wiktionary.org/wiki/assuaged
/əˈsweɪdʒ/
potolită, a potoli

arose:: 5 https://en.wiktionary.org/wiki/arose s-a ivit

amid:: 5 https://en.wiktionary.org/wiki/amid în mijlocul

uproar:: 5 https://en.wiktionary.org/wiki/uproar zarvă

contended:: 5 https://en.wiktionary.org/wiki/contended înfruntat

dismayed:: 5 https://en.wiktionary.org/wiki/dismayed descurajat nspaimntat alteration of Old French esmaier (“to frighten”), probably from Vulgar Latin *exmagare (“to deprive (someone) of strength, to disable”) 

stern:: 5 https://en.wiktionary.org/wiki/stern sever aspru

mere:: 5 https://en.wiktionary.org/wiki/mere nu mai mult de

rippling:: 5 https://en.wiktionary.org/wiki/rippling clipocit

quenched:: 5 https://en.wiktionary.org/wiki/quenched potoli

utterly:: 5 https://en.wiktionary.org/wiki/utterly absolut complet

variance:: 5 https://en.wiktionary.org/wiki/variance în dezacord

chiefly:: 5 https://en.wiktionary.org/wiki/chiefly în special

clamorous:: 5 https://en.wiktionary.org/wiki/clamorous gălăgios

essayed:: 5 https://en.wiktionary.org/wiki/essayed încerca a înainta

drown:: 5 https://en.wiktionary.org/wiki/drown înecat

midst:: 5 https://en.wiktionary.org/wiki/midst mijlocul

strife:: 5 https://en.wiktionary.org/wiki/strife ceartă

behold:: 5 https://en.wiktionary.org/wiki/behold a privi

ceased:: 5 https://en.wiktionary.org/wiki/ceased încetat oprit

gazed:: 7 https://en.wiktionary.org/wiki/gazed privire fixa

minstrelsy:: 7 https://en.wiktionary.org/wiki/minstrelsy bard

conceived:: 7 https://en.wiktionary.org/wiki/conceived conceput

propounded:: 7 https://en.wiktionary.org/wiki/propounded propune

wherein:: 7 https://en.wiktionary.org/wiki/wherein unde

wisdom:: 7 https://en.wiktionary.org/wiki/wisdom intelepciune

bent:: 7 https://en.wiktionary.org/wiki/bent indoit curbat

feigned:: 7 https://en.wiktionary.org/wiki/feigned simulat

thinther:: 7 https://en.wiktionary.org/wiki/thither acolo

turmoils:: 7 https://en.wiktionary.org/wiki/turmoils perioade grele stare de haos

subdue:: 7 https://en.wiktionary.org/wiki/subdue supune

envying:: 7 https://en.wiktionary.org/wiki/envying invidie from Old French envie, from Latin invidia (“envy”)

rejoiced:: 8 https://en.wiktionary.org/wiki/rejoiced s-a bucurat

unquiet:: 8 https://en.wiktionary.org/wiki/unquiet tulburat

praised:: 8 https://en.wiktionary.org/wiki/praised laudat  borrowed from Old French proisier, preisier (“to value, prize”), from Late Latin pretiō (“to value, prize”) from pretium (“price, worth, reward”)

deed:: 8 https://en.wiktionary.org/wiki/deed fapta contract

hoards:: 8 https://en.wiktionary.org/wiki/hoards comoara a stringe a aduna Cognate with German Hort (“hoard; refuge”)

wrought:: 9 https://en.wiktionary.org/wiki/wrought forjat ornamentat

fulfilment:: 9 https://en.wiktionary.org/wiki/fulfilment realizare

thenceforward:: 10 https://en.wiktionary.org/wiki/thenceforward de atunci inainte

astounded:: 10 https://en.wiktionary.org/wiki/astounded uluit

naught:: 10 https://en.wiktionary.org/wiki/naught nimic (archaic) Nothingness

meddled:: 10 https://en.wiktionary.org/wiki/meddled amestecat from Latin misceō (“to mix”)

coveted:: 10 https://en.wiktionary.org/wiki/coveted rîvni

strife:: 10 https://en.wiktionary.org/wiki/strife ceartă

hue:: 11 https://en.wiktionary.org/wiki/hue

raiment:: 11 https://en.wiktionary.org/wiki/raiment haine (archaic or literary) Clothing

clad:: 11 https://en.wiktionary.org/wiki/clad imbracat

tumults:: 12 https://en.wiktionary.org/wiki/tumults zarva tulburare From Latin tumultus (“noise, tumult”)  

endeavoured:: 12 https://en.wiktionary.org/wiki/endeavoured s-a straduit

delved:: 12 https://en.wiktionary.org/wiki/delved a scotocit

enamoured:: 15 https://en.wiktionary.org/wiki/enamoured

manifold:: 15 https://en.wiktionary.org/wiki/manifold variat

delight:: 16 https://en.wiktionary.org/wiki/delight incintare bucurie delectare from Latin delectare (“to delight, please”)

swift:: 16 https://en.wiktionary.org/wiki/swift iute rapid

bidding:: 16 https://en.wiktionary.org/wiki/bidding oferta invitatie somare

dread:: 17 https://en.wiktionary.org/wiki/dread teama groaza

strides:: 17 https://en.wiktionary.org/wiki/strides a merge cu pasi mari

helm:: 17 https://en.wiktionary.org/wiki/helm cirma

shimmering:: 17 https://en.wiktionary.org/wiki/shimmering licarire a luci

nonetheless:: 17 https://en.wiktionary.org/wiki/nonetheless cu toate acestea

shores:: 17 https://en.wiktionary.org/wiki/shores tarmuri

firths:: 17 https://en.wiktionary.org/wiki/firths limanuri

longing:: 17 https://en.wiktionary.org/wiki/longing dor

griefs:: 17 https://en.wiktionary.org/wiki/griefs dureri from Latin gravis (“heavy, grievous, sad”)

smith:: 17 https://en.wiktionary.org/wiki/smith fierar

gems:: 18 https://en.wiktionary.org/wiki/gems bijuterii from Latin gemma (“a swelling bud; a jewel; gem”)

mockery:: 18 https://en.wiktionary.org/wiki/mockery bataie de joc  Middle French mocquerie, moquerie, from moquer, moker (“to mock”) + -erie (“-ery”), perhaps from Greek μωκός (mokós, “mocker”)

spouse:: 18 https://en.wiktionary.org/wiki/spouse sotia aphesis from Latin spōnsus m (“bridegroom”), spōnsa f (“bride”)

moss:: 18 https://en.wiktionary.org/wiki/moss muschi  Latin muscus (“moss”)

mould:: 18 https://en.wiktionary.org/wiki/mould mucegai from Latin modulus

robed:: 18 https://en.wiktionary.org/wiki/robed invesmintata

dew:: 18 https://en.wiktionary.org/wiki/dew roua

barrent:: 18 https://en.wiktionary.org/wiki/barrent sterp

slain:: 19 ucisi

burden:: 19 https://en.wiktionary.org/wiki/burden 1. povara, greutate 2. refren

grief:: 19 https://en.wiktionary.org/wiki/grief  1. durere, mihnire, necaz from Latin gravis (“heavy, grievous, sad”)

mourns:: 19 https://en.wiktionary.org/wiki/mourns a plinge, a jeli

weep:: 19 https://en.wiktionary.org/wiki/weep 1. a deplinge 2. a musti, a zemui

steed:: 20 https://en.wiktionary.org/wiki/steed armasar

beard:: 20 https://en.wiktionary.org/wiki/beard barba

ruddy:: 20 https://en.wiktionary.org/wiki/ruddy rumen

dtreadful:: 20 https://en.wiktionary.org/wiki/dreadful inspaimintator

unwillingly:: 20 fara voie fara a vrea

scarlet:: 20 https://en.wiktionary.org/wiki/scarlet stacojiu

forfeited:: 23 https://en.wiktionary.org/wiki/forfeited 1. amenda 2. pierdere a drepturilor 3. confiscare

malice:: 23 https://en.wiktionary.org/wiki/malice rautate  from Latin malitia (“badness, bad quality, ill-will, spite”), from malus (“bad”).

coeval:: 23 https://en.wiktionary.org/wiki/coeval contemporan Late Latin coaevus, from Latin con- (“equal”) + aevum (“age”).

squandered:: 23 https://en.wiktionary.org/wiki/squandered risipi

coveted:: 23 https://en.wiktionary.org/wiki/coveted rivnit

allegiance:: 23 https://en.wiktionary.org/wiki/allegiance fidel

treacherous:: 23 https://en.wiktionary.org/wiki/treacherous perfid

scourges:: 23 https://en.wiktionary.org/wiki/scourges flageluri from Vulgar Latin excorrigiare, consisting of ex- (“thoroughly”) + corrigia (“thong, whip”)

lore:: 23 https://en.wiktionary.org/wiki/lore invatatura

deceits:: 23 https://en.wiktionary.org/wiki/deceits inselatorii from Latin dēcipere (“to cheat, mislead”)

cunning:: 23 https://en.wiktionary.org/wiki/cunning viclenie

ere:: 27 https://en.wiktionary.org/wiki/ere mai inainte

hardihood:: 27 https://en.wiktionary.org/wiki/hardihood indrazneala

wrath:: 27 https://en.wiktionary.org/wiki/wrath minie

brooded:: 27 https://en.wiktionary.org/wiki/brooded

devised:: 27 https://en.wiktionary.org/wiki/devised inceput  from Vulgar Latin devisō, from Latin dīvisō, frequentative of dīvidō.

primeval:: 27 https://en.wiktionary.org/wiki/primeval primitiv from Latin primaevus (“in the first or earliest period of life”), from primus (“first”) + aevum (“time, age”); see prime and age.

twilight:: 28 https://en.wiktionary.org/wiki/twilight amurg

weary:: 28 https://en.wiktionary.org/wiki/weary obosit

hatred:: 28 https://en.wiktionary.org/wiki/hatred

deemed:: 28 https://en.wiktionary.org/wiki/deemed prezumtia

delving:: 29 https://en.wiktionary.org/wiki/delving intrarea

marred:: 29 https://en.wiktionary.org/wiki/marred schimonosita

rotted:: 29 https://en.wiktionary.org/wiki/rotted putrezita

choked:: 29 https://en.wiktionary.org/wiki/choked sufoca

weeds:: 29 https://en.wiktionary.org/wiki/weeds buruieni

struck:: 29 https://en.wiktionary.org/wiki/struck lovi

blow:: 29 https://en.wiktionary.org/wiki/blow suflare

abiding:: 30 https://en.wiktionary.org/wiki/abiding respectabil

slender:: 31 https://en.wiktionary.org/wiki/slender subtire

dappled:: 31 https://en.wiktionary.org/wiki/dappled pestrit

fluttering:: 31 https://en.wiktionary.org/wiki/fluttering filfit

glittering:: 31 https://en.wiktionary.org/wiki/glittering scinteietor

swung:: 31 https://en.wiktionary.org/wiki/swung legana

blossom:: 31 https://en.wiktionary.org/wiki/blossom inflorire

waxed:: 31 https://en.wiktionary.org/wiki/waxed ceara

faint:: 32 https://en.wiktionary.org/wiki/faint lesin