= The War of the Worlds, by H. G. Wells

eve:: 1 ajun

keenly:: 1 cu mare atenție

scrutinised:: 1 scrutat

transient:: 1 trecător

swarm:: 1 mișuna

complacency:: 1 mulțumire de sine

serene:: 1 calmi

fro:: 1

infusoria:: 1infuzorii

fancied:: 1 imaginat

perish:: 1 pierit

envious:: 1 invidios

scarcerly:: 1 nu prea; abia

revolves:: 1 învîrti

ceased:: 2 a încetat

molten:: 2 turnat

vain:: 2 orgolios

attenuated:: 2 ușurat

shrunk:: 2 micșorat

snowcaps:: 2

melt:: 2 topit

exhaustion:: 2 epuizare

sunward:: 2

eloquent:: 2 grăitor

glimpses:: 2 licăriri

cloud-wisps:: 3 manunchi de nori

incessant:: 3 continuu

struggle:: 3 luptă

warfare:: 3 război

creeps:: 3 înfiorare

harshly:: 3 aspru

ruthless:: 3 nemilos

utter:: 3 total

wrought:: 3 forjat

swept:: 3 măturat

apostles:: 3 apostoli

warred:: 3 războit

descent:: 3 coborîre

markings:: 3 indicații

casting:: 4 turnare

pit:: 4 gaură

peculiar:: 4 specific

outbreak:: 4 izbucnire

vigil:: 4 veghe

feeble:: 4 plăpind

glow:: 4 licărire

steady:: 4 stabil

slit:: 4 crăpătură

oblong:: 4 alungit

streaked:: 4 dungă

faintly:: 5 slab

stripes:: 5 dungă

flatened:: 5

pin:: 5 ac

quivered:: 5 tremurat

recede:: 5 retrage

unfathomable:: 5 nepătruns

swiftly:: 5 repede

unerring:: 5 unfailibil

reddish:: 5 roșiatic

flash:: 5 fulger

slightest:: 5 neînsemnat

clumsily:: 5 stîngaci

streamer:: 5 flamură

patches:: 5 bucăți

crimson:: 5 stacojiu

gleam:: 6 licărire

lit:: 6 aprins

scoffed:: 6 batjocori

shunting:: 7 manevra

rumbling:: 7 horoitor

tranquil:: 7 calm