= The War of the Worlds, by H. G. Wells

eve:: 1 ajun

keenly:: 1 cu mare atenție

scrutinised:: 1 scrutat

transient:: 1 trecător

swarm:: 1 mișuna

complacency:: 1 mulțumire de sine

serene:: 1 calmi

fro:: 1

infusoria:: 1infuzorii

fancied:: 1 imaginat

perish:: 1 pierit

envious:: 1 invidios

scarcerly:: 1 nu prea; abia

revolves:: 1 învîrti

ceased:: 2 a încetat

molten:: 2 turnat

vain:: 2 orgolios

attenuated:: 2 ușurat

shrunk:: 2 micșorat

snowcaps:: 2

melt:: 2 topit

exhaustion:: 2 epuizare

sunward:: 2

eloquent:: 2 grăitor

glimpses:: 2 licăriri

cloud-wisps:: 3 manunchi de nori

incessant:: 3 continuu

struggle:: 3 luptă

warfare:: 3 război

creeps:: 3 înfiorare

harshly:: 3 aspru

ruthless:: 3 nemilos

utter:: 3 total

wrought:: 3 forjat

swept:: 3 măturat

apostles:: 3 apostoli

warred:: 3 războit

descent:: 3 coborîre

markings:: 3 indicații

casting:: 4 turnare

pit:: 4 gaură

peculiar:: 4 specific

outbreak:: 4 izbucnire

vigil:: 4 veghe

feeble:: 4 plăpind

glow:: 4 licărire

steady:: 4 stabil

slit:: 4 crăpătură

oblong:: 4 alungit

streaked:: 4 dungă

faintly:: 5 slab

stripes:: 5 dungă

flatened:: 5

pin:: 5 ac

quivered:: 5 tremurat

recede:: 5 retrage

unfathomable:: 5 nepătruns

swiftly:: 5 repede

unerring:: 5 unfailibil

reddish:: 5 roșiatic

flash:: 5 fulger

slightest:: 5 neînsemnat

clumsily:: 5 stîngaci

streamer:: 5 flamură

patches:: 5 bucăți

crimson:: 5 stacojiu

gleam:: 6 licărire

lit:: 6 aprins

scoffed:: 6 batjocori

shunting:: 7 manevra

rumbling:: 7 horoitor

tranquil:: 7 calm

hissing:: 9 fîsîit; șuierat

persuaded:: 9 convins

gravel:: 9 pietriș

flung:: 9 aruncat

heath:: 10 pîrloaga

heather:: 10

heaps:: 10 grămezi

dawn:: 10 zori

splinters:: 10 așchii

fir:: 10 brad

shivered:: 10 înfiorat

caked:: 10 încleiat

scaly:: 10 solzos

dun-coloured:: 10 sir

stirring:: 10 agitat

hollow:: 10 găunos

cindery:: 10 moale

clinker:: 10

ashy:: 10 sclipitor

muffled:: 11 înăbușit

grating:: 11 zgîrîia

confied:: 11 înggrădit

dreadful:: 11 înspăimîntător

dull:: 11 greoi

irresolute:: 11 nehotărît

scrambled:: 11 cățărat

potman:: 11

sobered:: 11 sobru

palings:: 11 gard

deaf:: 12 surd

snatched:: 12 înhățat

rapped:: 12 lovi ușor

scale:: 12 crustă

stick:: 12 băț

shutters:: 12 pleoape

startled:: 12 speriat

bulk:: 13 grămadă

turf:: 13 iarba

charred:: 13 făcut cărbune

loafers:: 13 leneși

faint:: 13 slab

rusty:: 14 ruginit

gleamed:: 14 licări

crack:: 14 crăpătura

hue:: 14 culoare

lordly:: 14 pompos

carriage:: 14 trăsură

glaringly:: 15

streamers:: 15 flamuri

barrow-load:: 15 roabă

wielding:: 15 mînuire

spades:: 15 hîrlețe

pickaxes:: 15 tîrnăcopuri

pitched:: 15 înălbit

crimson:: 15 stacojiu

perspiration:: 15 sudoare

manor:: 15 moșie

railing:: 15 gard

stirring:: 15

tumult:: 15 zarvă

common:: 17 islaz, parc

elbowing:: 17

jostling:: 17 ghionti

swayed:: 17 legănat

humming:: 17 bîzîit

blundered:: 18 a face o gafă

screw:: 18 șurub

consussion:: 18 izbitură

stirring:: 18 agitat

billowy:: 18

coiled:: 18 înfășurat

writhing:: 18 zvîrcoli

wriggled:: 18 șerpuit

chill:: 18 frig

shriek:: 18 țipăt

glistened:: 18

brim:: 18 margine

quivered:: 18 freamăt

panted:: 18 gîfîit

heaved:: 18 agitat

lank:: 18 deșirat

ridges:: 19 punți

chin:: 19 bărbie

wedge-like:: 19 ca pana

incessant:: 19 neîncetat

nausea:: 19 amețeală

fungoid:: 19

clumsy:: 19 stîngaci

tedious:: 19 incomod

glimpse:: 19 scăpărare

toppled:: 19 răsturnat

thud:: 19 bubuitură

forthwith:: 19 îndată

aperture:: 19 deschizătură

rigour:: 19 asprime

slantingly:: 19

stumbling:: 19 împiedicare

avert:: 19 îndepărta

furze:: 19

panting:: 19 gîfîind

bobbing:: 19 țopai

overruled:: 20

dwindling:: 20

ditches:: 20 șanturi

hdges:: 20 gard viu

shouts:: 20 țipete

derelict:: 20 abandonat

glimpse:: 21 privire

knee-deep:: 21

mound:: 21 movilă

longing:: 21 dor

vantage:: 21 avantaj

leash:: 21 lesă

rod:: 21 tijă

apex:: 21 vîrf

spun:: 21 țesut

wobbling:: 21

knoll:: 22 creastă

faint:: 22

dusk:: 22 amurg

intermittent:: 22 întrerupt

stillness:: 22 liniște

twos:: 22 perechi

boldly:: 22

clatter:: 22 zăngănit

hoots:: 22 copite

lad:: 22 tînăr

trundling:: 22 rostogoli

hasty:: 22 primpit

flutter:: 22 fîlfîit

inward:: 22 spre interior

dim:: 23 neclar

hazy:: 23 neclar

puffs:: 23 nori

hissing:: 23 fîsîi

glare:: 23 stralucire

leaping:: 23 sălta

staggering:: 23

shaft:: 23 săgeată

burst:: 23 explodat

dull:: 23

stir:: 24 urni

squeal:: 24 țipăt

stilled:: 24

dumbfounded:: 24 zăpăcit

dazzled:: 24 orbit

mustering:: 24

wobbled:: 24 clătinat

umanning:: 25 descurajat

persuasion:: 25 convingere

verge:: 25 margine

leap:: 25 sări

chamber:: 27 cameră

beam:: 27 rază

polished:: 27 lustruită

brushed:: 27 curățat

novelty:: 27 noutate

hum:: 28 murmur

gloaming:: 28 asfințit

spinning:: 28

deter:: 28 a opri

booing:: huiduit

hummock:: 28 movilă

droning:: 29 zumzăi

swung:: 29 legănat

crumbling:: 29 surpa

gable:: 29 fronton

twigs:: 29 copaci

bolted:: 29 zăvorît

flock:: 29 turmă

jammed:: 29 bruiat

tramplet:: 29 tescuit

blundering:: 31 greșind

pitiless:: 31 nemilos

whirling:: 31 roti

flourishing:: 31

cross-roads:: 31

staggered:: 31 bălăbănit

perplexed:: 31 nedumerit

garment:: 31 haine

burst:: 31 explodat

feebleness:: 31

anguish:: 31 chin

unsteadly:: 31

steep:: 31 abrupt

mumblet:: 32 mormăit

billowing:: 32 unduit

caterpillar:: 32 omidă

firelit:: 32

gables:: 32

serenity:: 32 seninătate

yonder:: 32 de acolo

abart:: 32 scrîntire

startled:: 33 speriat

neglected:: 33 neglijat

sluggish:: 33 grea

cope:: 33

reassuring:: 34 liniști

vividness:: 34 însuflețire

lorder:: 34

nest:: 34 cuib

pitiless:: 34 nemilos

topple:: 35 răsturnat

canarad:: 34

lanes:: 34

whirl:: 35 vîrtej

shunting:: 35 manevră

alighting:: 36 coborîre

mingled:: 36 contopit

tidings:: 36 vești

rattling:: 36 rapid

veil:: 36 val

lingered:: 36

smouldering:: 37 mocni

fringe:: 37

clog:: 37

vein:: 37

stirring:: 37 agitat

indefatigable:: 37 neobosit

whirled:: 37 învîrti

starlit:: 37

lassitude:: 39 moleșeală

lar:: 39

rattle:: 39 hîrîit

chariot:: 39 car

chatted:: 39 pălăvrăgi

strolled:: 39 cutreierat

fence:: 39 gard

calf:: 40

plied:: 40 asaltat

darned:: 40

carn:: 40

glimpse:: 41 privire

dull:: 41

lawn:: 42 gazon

clattering:: 42 zornăi

astonished:: 43 surprinși

bevy:: 43 grup

palings:: 43

scent:: 45 miros

hay:: 45 fîn

lush:: 45 copios

hedges:: 45

feverishly:: 45 fertil

fusillade:: 45 salvă

lurid:: 47 înflăcări

tug:: 47 smuncitură

reins:: 47 frîu

pierced:: 47 gaurit

thunder:: 47 tunes

hail:: 47 cădea

smote:: 47 strînge

gustily:: 47

milking-stool:: 48 scaun de muls

tilted:: 48

brittle:: 48 fragil

reeds:: 48

thrusting:: 48 împinge

snapped:: 48 frînt

wrenched:: 48 forțat

shafts:: 48 tijele

flung:: 48 aruncat

shallow:: 48 superficial

crouched:: 48 gehmuit

clump:: 48 bulgare

furze:: 48

striding:: 48 cu pași mari

mere:: 48 simplu

insenate:: 48 nesăbuit

pace:: 48

brazen:: 48

surmounted:: 48 stapînit

howl:: 49 urlet

stooping:: 49 aplecare

soaked:: 49 îmbibat

hail:: 49 grindină

puddle-water:: 49

astonishment:: 49

peril:: 49 primejdie

squatter:: 49 fermier

hut:: 49 cabană

patch:: 49 petec

hammered:: 49 ciocanit

desisted:: 49 renunțat

availing:: 49 inutil

ditch:: 49

shivering:: 49 zgribulit

study:: 53 birou
scud:: 53
torpor:: 55 apatie
unfastened:: 55 descuia
stiff:: 55 betivan
scob:: 55 oftat
weep:: 55 plinge
peeping:: 56 privi pe furis
furtively:: 56
leisurely:: 56 incet
cowled:: 56
scintillated:: 57 sclipi
waddle:: 57 mers clatinat
skulking:: 57
mutton:: 58 carne de berbec
pantry:: 58
dwindled:: 58 scazut
gaunt:: 58 slabanog
wreckage:: 58 ramasite
dawn:: 59 zori
forthwith:: 59
ransack:: 59 rascoli
chimney-tops:: 60 virfuri de hornuri
lane:: 60 straduta
scorch:: 60 pirjoli
eager:: 61 nerabdator
cotage:: 62
creakily:: 62
byflett:: 63
score of hussars:: 63 multi husari
omnibus:: 63
cellars:: 64 pivnite
jesting:: 65 glumind
inn:: 65 han
yelping:: 65 care latra
meadows:: 65
burden:: 66 povara
shoted:: 66 strigat
unheeded:: 66 nebagat in seama
muddy:: 66 noroios
slippery:: 66 lunecos
unvailingly:: 68
haste:: 71 graba
encumbered:: 71 impovarat
sally:: 72 atac
sodden:: 72 ud
oars:: 72
brevity:: 77 concizie
pouring:: 79 siroind
loafers:: 81
smite:: 82 doboara
attic:: 85 mansarda
craned:: 86 intins
garment:: 86 haina
bawling:: 86 racni
rubbing:: 87 frecau
aimless:: 87 fara rost
hastly:: 87 graba
mingling:: 87 amestec
smothered:: 87
mist:: 91 ceata
dewy:: 91 rourat
nettles:: 91
crescent:: 91 corn
wading:: 95 a-si face drum
sparing:: 96 econom
frantic:: 96 nebunesc
roaring:: 99
lashing:: 99 fulgerind
foaming:: 99 spumega
footstore:: 107
groans:: 107
tap:: 108 robinet
flung:: 109
intinsclutching:: 109
hoofs:: 109
rim:: 109 obada
slashed:: 109
collar:: 109 guler
lugged:: 109 trage
clutched:: 109 apucat
breadth:: 110
weeping:: 110
wrteched:: 110
din:: 110 galagie
swarming:: 110
blotting-paper:: 114 sugativa
hamstringing:: 114 a schilodi
thinning:: 114
remnant:: 114
morrow:: 115
seized:: 116 sechestru
lurking:: 123 pindind
whither:: 123 unde
fled:: 123 refugiat
aching:: 123 dureros
paced:: 123 masurat
circumspection:: 123
hemmed:: 124 inconjurat
slamming:: 124 trinti
scalded:: 124 fript
sodden:: 124
rags:: 124 cirpe
flannel:: 124 flonela
contorted:: 125 rasucit
cindery:: 125
misadevnture:: 125 accidente
lull:: 125 ragaz
heap:: 125
aghast:: 126 ingrozit
perished:: 126
shed:: 126 sura
curate:: 126 vicar
stir:: 126
foolhardy:: 126 cutezator
hatchet:: 127 baltag
walled:: 127 zidit
ham:: 127 jambon
fancy:: 128
quiver:: 130
scullery:: 131 bucatarioara
dozed:: 131 motait
aperture:: 131
tranquil:: 131
plaster:: 131 ghips
rampart:: 131
slender:: 134 subtirel
entrails:: 134 intestine
nourishment:: 135 hrana
pent:: 141
flinging:: 143 aruncat
shrieking:: 144
lurked:: 145
I gripped myself with both hand:: 145
encampment:: 145
howling:: 146
tussle:: 147
desisted:: 147
cajoled:: 147
bribe:: 147
babbling:: 147
butt:: 149 pat
lump of coal:: 151 bucata de carbune
creeping:: 151 tiri
parched:: 153 uscat
ebbed:: 153
throat:: 153 gitlej
rainted:: 153 retinut
rambling:: 153 ratacitor
dozed:: 153 motai
keen:: 153 puternic
tottering:: 157 care se clatina
mound:: 157 movila
noisome:: 157 daunator
den:: 157 vizuina
lurid:: 157 in flacari
inkling:: 157 aluzie
tangle:: 158
weed:: 158
succumb:: 159
slake:: 159
needless:: 161
latch:: 161
grim:: 162
cutlass:: 163
culvert:: 164
skedaddle:: 169
parleyed:: 171
reconnoitre:: 174
wailing:: 179
maggots:: 179
mongrels:: 180
dissuaded:: 188
tramps:: 189
swayed:: 192
reckless:: 193


